### Registro
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{"nombre": "ejemplo3", "tel": "123456789", "email": "ejemplo3@example.com",  "password": "Password123"}

### Login

POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{"email": "ejemplo3@example.com", "password": "Password123"}


### Perfil

GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=50f047ac3d2436708bed986ade54abad7ac972d0

### Actualización perfil

PUT http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=50f047ac3d2436708bed986ade54abad7ac972d0

{"nombre": "nuevoNombre", "tel": "123456789", "email": "ejemplo@example.com", "password": "Password123"}

### Actualización parcial
PATCH http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=50f047ac3d2436708bed986ade54abad7ac972d0

{"nombre": "nuevoNombre2"}



### Logout

DELETE http://127.0.0.1:8000/api/users/logout/
Content-Type: application/json
Cookie: session=2310cc593da24c0de99577620e406987219a26e0


### Baja

DELETE http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Cookie: session=2310cc593da24c0de99577620e406987219a26e0


