# Generated by Django 4.2.11 on 2024-05-03 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("films", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="rating",
            new_name="release_year",
        ),
        migrations.RemoveField(
            model_name="film",
            name="release_date",
        ),
        migrations.AddField(
            model_name="film",
            name="global_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="films.film"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
