# Generated by Django 4.2.11 on 2024-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0002_rename_rating_film_release_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="image_url",
            field=models.URLField(
                default="https://th.bing.com/th/id/R.51879f9aeaaf6060aa42a64df71696f1?rik=h8Ox9c2rUwGi%2fg&pid=ImgRaw&r=0"
            ),
        ),
    ]
