# Generated by Django 4.2.11 on 2024-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0003_film_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
