# Generated by Django 4.2.11 on 2024-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("films", "0004_alter_film_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="global_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
